{
 "title": "Nvidia GPU",
 "description": "GPU dashboard for nvidia metrics ",
 "tags": [
  "gpu",
  "kubernetes-mixin"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP, instance)"
    }
   },
   {
    "name": "gpu",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP, gpu)"
    }
   },
   {
    "name": "mig",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP, GPU_I_PROFILE)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info{}, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU / RAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{node=~\"$node\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Memory Usage (w/o cache)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", node=~\"$node\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\".+\", node=~\"$node\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\".+\", node=~\"$node\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "IOPS(Reads+Writes)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ceil(sum by(namespace) (rate(container_fs_reads_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", node=~\"$node\", namespace!=\"\"}[$__rate_interval]) + rate(container_fs_writes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", node=~\"$node\", namespace!=\"\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "ThroughPut(Read+Write)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by(namespace) (rate(container_fs_reads_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", node=~\"$node\", namespace!=\"\"}[$__rate_interval]) + rate(container_fs_writes_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", node=~\"$node\", namespace!=\"\"}[$__rate_interval]))",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "GPU Allocations by Namespace",
   "type": "state-timeline",
   "description": "Shows the number of GPU resources assigned to pods per namespace. An assigned GPU is considered to be \"in-use\" no matter whether it's actually being utilized (use the graph below to check that). An assigned GPU therefore cannot be used by anybody else! The GPU counts as \"assigned\" if the pod has been assigned to a node. Pending, completed and failed pods do not count. Consequently, a pod which fails to start for whatever reason (e.g. failing to pull container image) does consume GPU resources, as it has been assigned to a node!\n\nUnassigned, i.e. pending pods, are shown in gray.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$node\", resource=~\"nvidia_com_gpu\"} * on (namespace, pod, cluster) group_left () max by (namespace, pod, cluster) ((kube_pod_status_phase{phase=~\"Running\"} == 1))) by (namespace, node, pod) > 0",
     "legendFormat": "{{node}}|{{namespace}} |{{pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$node\", resource=~\"nvidia_com_gpu\"} * on (namespace, pod, cluster) group_left () max by (namespace, pod, cluster) ((kube_pod_status_phase{phase=~\"Pending\"} == 1))) by (namespace, resource, pod) > 0",
     "legendFormat": "--pending-- {{resource}}|{{namespace}}|{{pod}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(DCGM_FI_DEV_GPU_UTIL{instance=~\"$instance\"}) by (instance, gpu)) / count(count(DCGM_FI_DEV_GPU_UTIL{instance=~\"$instance\"}) by (instance, device))"
    }
   ]
  },
  {
   "title": "GPU Frame Buffer",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED{instance=~\"$instance\", gpu=~\"$gpu\"})/sum(DCGM_FI_DEV_FB_USED{instance=~\"$instance\", gpu=~\"$gpu\"}+DCGM_FI_DEV_FB_FREE{instance=~\"$instance\", gpu=~\"$gpu\"})"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{GPU_I_PROFILE=\"\",instance=~\"$instance\", gpu=~\"$gpu\"}) BY (instance, gpu)",
     "legendFormat": "{{instance}}-full{{gpu}}"
    },
    {
     "expr": "AVG(DCGM_FI_DEV_GPU_UTIL{GPU_I_PROFILE!=\"\",instance=~\"$instance\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"}) BY (instance, gpu)",
     "legendFormat": "{{instance}}-mig{{gpu}}"
    }
   ]
  },
  {
   "title": "SM clock frequency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": " AVG(DCGM_FI_DEV_SM_CLOCK{instance=~\"$instance\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"}*1000000) BY (instance, gpu)",
     "legendFormat": "{{instance}}-gpu{{gpu}}-tensor"
    }
   ]
  },
  {
   "title": "# GPUs / MIGs",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(label_replace(DCGM_FI_DEV_GPU_UTIL{instance=~\"$instance\",GPU_I_PROFILE!=\"\"}, \"GPU\",\"$1\",\"GPU_I_PROFILE\",\"(.*)\")) by (instance,GPU)",
     "legendFormat": "{{ GPU }}"
    },
    {
     "expr": "count(label_replace(DCGM_FI_DEV_GPU_UTIL{instance=~\"$instance\",GPU_I_PROFILE!=\"\"} >= 0.5, \"GPU\",\"$1\",\"GPU_I_PROFILE\",\"(.*)\")) by (instance,GPU)",
     "legendFormat": "{{ GPU }}"
    },
    {
     "expr": "count(label_replace(DCGM_FI_DEV_GPU_UTIL{instance=~\"$instance\",GPU_I_PROFILE=\"\"}, \"GPU\",\"$1\",\"modelName\",\"(.*)\")) by (GPU)",
     "legendFormat": "{{ GPU }}"
    },
    {
     "expr": "count(label_replace(DCGM_FI_DEV_GPU_UTIL{instance=~\"$instance\",GPU_I_PROFILE=\"\"} >= 0.5, \"GPU\",\"$1\",\"modelName\",\"(.*)\")) by (GPU)",
     "legendFormat": "{{ GPU }}"
    }
   ]
  },
  {
   "title": "Frame Buffer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_FB_FREE{GPU_I_PROFILE=\"\",instance=~\"$instance\", gpu=~\"$gpu\"}/(DCGM_FI_DEV_FB_FREE{GPU_I_PROFILE=\"\",instance=~\"$instance\", gpu=~\"$gpu\"}+DCGM_FI_DEV_FB_USED{GPU_I_PROFILE=\"\",instance=~\"$instance\", gpu=~\"$gpu\"})) BY (instance, gpu)",
     "legendFormat": "{{instance}}-full{{gpu}}"
    },
    {
     "expr": "AVG(DCGM_FI_DEV_FB_FREE{GPU_I_PROFILE!=\"\",instance=~\"$instance\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"}/(DCGM_FI_DEV_FB_FREE{GPU_I_PROFILE!=\"\",instance=~\"$instance\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"}+DCGM_FI_DEV_FB_USED{GPU_I_PROFILE!=\"\",instance=~\"$instance\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"})) BY (instance, gpu)",
     "legendFormat": "{{instance}}-mig{{gpu}}"
    }
   ]
  },
  {
   "title": "Memory clock frequency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_MEM_CLOCK{instance=~\"$instance\", gpu=~\"$gpu\", GPU_I_PROFILE=~\"$mig\"}*1000000) BY (instance, gpu)",
     "legendFormat": "{{instance}}-gpu{{gpu}}-active"
    }
   ]
  },
  {
   "title": "# Timeslicing",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$instance\",resource=~\"nvidia_com_gpu\"}) by (node,resource)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{node=~\"$instance\",resource=~\"nvidia_com_gpu\"}) by (node,resource)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL{instance=~\"${instance}\", gpu=~\"${gpu}\", namespace!=\"\"}) by (instance, gpu, GPU_I_ID, GPU_I_PROFILE, namespace, container)",
     "legendFormat": "{{kubernetes_node}} GPU {{gpu}}-{{GPU_I_ID}} {{GPU_I_PROFILE}} {{namespace}} {{container}}"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Mem Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED{instance=~\"${instance}\", gpu=~\"${gpu}\", namespace!=\"\"}) by (instance, gpu, GPU_I_ID, GPU_I_PROFILE, namespace, container)",
     "legendFormat": "{{kubernetes_node}} GPU {{gpu}}-{{GPU_I_ID}} {{GPU_I_PROFILE}} {{namespace}} {{container}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "AVG(DCGM_FI_DEV_GPU_TEMP{instance=~\"$instance\", gpu=~\"$gpu\"}) BY (instance, gpu)",
     "legendFormat": "{{instance}}-gpu{{gpu}}"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "AVG(DCGM_FI_DEV_POWER_USAGE{instance=~\"$instance\", gpu=~\"$gpu\"}) BY (instance, gpu)",
     "legendFormat": "{{instance}}-gpu{{gpu}}"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "-DCGM_FI_DEV_MEM_COPY_UTIL{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "{{instance}}-gpu{{gpu}}-Tx"
    },
    {
     "expr": "DCGM_FI_DEV_MEM_COPY_UTIL{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "{{instance}}-gpu{{gpu}}-Rx"
    }
   ]
  },
  {
   "title": "Cycles Memory Interface",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "AVG(DCGM_FI_PROF_DRAM_ACTIVE{instance=~\"$instance\", gpu=~\"$gpu\"}) BY (instance, gpu)",
     "legendFormat": "{{instance}}-gpu{{gpu}}"
    }
   ]
  }
 ]
}